name:                picrochole
version:             0.1.0
license:             GPL-3.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2019 barsanges

extra-source-files:
- README.md

synopsis:            A game engine to simulate pre-19th century warfare at the operational level
description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- containers
- time

library:
  source-dirs: src