name:                picrochole
version:             0.1.0
license:             GPL-3.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2022 barsanges

extra-source-files:
- README.md
- LICENSE

synopsis:            Game inspired by Le Vol de l'Aigle
description:         Please see the README

dependencies:
- base
- vector

library:
  source-dirs: src