name:                picrochole
version:             0.1.0
license:             GPL-3.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2022 barsanges

synopsis:            Game inspired by Le Vol de l'Aigle
description:         Please see the README

dependencies:
- aeson
- base
- containers
- directory
- filepath
- search-algorithms
- text
- vector

library:
  source-dirs: src

executables:
  picrochole:
    source-dirs:      app
    main:             Main.hs
    dependencies:
    - optparse-applicative
    - picrochole

tests:
  functional:
    main:                Spec.hs
    source-dirs:         test/functional
    dependencies:
    - hspec
    - picrochole
    - QuickCheck

  end-to-end:
    main:                Spec.hs
    source-dirs:         test/end-to-end
    dependencies:
    - hspec
    - picrochole
    # L'exécutable picrochole est aussi une dépendance et doit être reconstruit avant de lancer le test
    # Un moyen est d'inclure l'exécutable dans les cibles du test : stack test picrochole:test:end-to-end picrochole:exe:picrochole
    - process
