name:                picrochole
version:             0.1.0
license:             GPL-3.0
author:              barsanges
maintainer:          https://github.com/barsanges
copyright:           2022 barsanges

synopsis:            Game inspired by Le Vol de l'Aigle
description:         Please see the README

dependencies:
- aeson
- base
- containers
- directory
- filepath
- search-algorithms
- text
- vector

library:
  source-dirs: src

tests:
  functional:
    main:                Spec.hs
    source-dirs:         test/functional
    dependencies:
    - hspec
    - picrochole
    - QuickCheck